---
title: "analysis_real"
author: "Flora Janku"
date: "2024-12-05"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("broom.mixed")
install.packages("ggeffects")
remove.packages("insight")
install.packages("insight")
install.packages('ggeffects', dependencies = TRUE)
install.packages("jtools")
install.packages("sjPlot")

```

```{r setup, include=FALSE}
library(tidyverse)
library(GGally)
library(lmerTest)
library(performance)
library(car)
library(sandwich)
library(lmtest)
library(skimr)
library(emmeans)
library(broom.mixed)
library(ggeffects)
library(jtools)
library(lattice)
library(sjPlot)

theme_set(theme_minimal())

```

## Loading df

```{r}
media_real <- read_csv("media_real.csv")

view(media_real)
glimpse(media_real)

```

## Data tidying

```{r}
# No missing values in condition, 1 missing value in contracept
skim(media_real$condition)
media_real %>%
  filter(gender == "Female") %>%
  skim(contracept)

# Typo in weight

z_scores <- (media_real$weight - mean(media_real$weight)) / sd(media_real$weight)
outliers <- media_real$weight[abs(z_scores) > 3]
print(outliers)


# No values between 10 and 20, values below 20 need to be replaced in the relevant group
skim(media_real$cycle_length)

media_real %>%
  ggplot() +
  aes(cycle_length) +
  geom_histogram()

# No duplicates
sum(duplicated(media_real$PARTICIPANT_ID))

# Counting participants
media_real %>%
  filter(gender == "Female", cycle_regular == "Yes", !is.na(contracept), !is.na(cycle_day)) %>%
  count()

media_real %>%
  filter(gender == "Female", cycle_regular == "Yes", contracept == "No", !is.na(cycle_day)) %>%
  count()

media_real %>%
  filter(gender == "Female", cycle_regular == "Yes", contracept == "Yes", !is.na(cycle_day)) %>%
  count()

descriptive_stats <- media_real %>%
  filter(gender == "Female", cycle_regular == "Yes", !is.na(contracept)) %>%
  mutate(Cycle_Status = ifelse(is.na(cycle_day), "nem adott meg", "megadott"),
         Group = ifelse(contracept == "Yes", "Fogamzásgátlás", "Nincs fogamzásgátlás")) 

count_data <- descriptive_stats %>%
  group_by(Group, Cycle_Status) %>%
  summarise(Count = n(), .groups = 'drop')


descriptive_stats %>%
  ggplot() +
  aes(x = Group, fill = Cycle_Status) +
  geom_bar(position = "stack") +
   geom_text(data = count_data, 
            aes(x = Group, y = Count, label = Count, group = Cycle_Status),
            position = position_stack(vjust = 0.5), color = "white") +
  labs(title = "Résztvevők fogamzásgátlási státusz és meglévő menstruációs ciklus adatok alapján",
       x = "Csoport",
       y = NULL,
       fill = "Ciklus információ") +
   scale_fill_manual(values = c("nem adott meg" = "chartreuse4", "megadott" = "skyblue"))

media_real %>%
  filter(gender == "Female", cycle_regular == "Yes") %>%
  summarize(meanAge = mean(age),
            sdAge = sd(age))

media_real %>%
  filter(gender == "Female", cycle_regular == "Yes", !is.na(contracept), !is.na(cycle_day), !is.na(eda_avg_baseline), !is.na(eda_avg_before_task)) %>%
           count()
```


## Calculating variables

```{r}
#Calculated PANAS, baseline MF and VS task performance change means
woman_normcycle <-
  media_real |> 
  # Dropping irrelevant and NA cases
  filter(gender == "Female", cycle_regular == "Yes", !is.na(contracept), !is.na(condition)) |> 
  mutate(# Setting baselines
         condition = fct_relevel(condition, "placebo"),
         contracept = fct_relevel(contracept, "No"),
         caffeine_perday = fct_relevel(caffeine_perday, c("I don't consume caffeine", "25-55 mg/day", "75-80 mg/day", "80-100 mg/day", "100-130 mg/day", "130-160 mg/day", "160-240 mg/day", "240-320 mg/day", "320-400 mg/day")),
         # Correcting typo in weight
         weight = ifelse(weight == 565, 56.5, weight),
         # Calculating scales
         panas_baseline_mean = (panas_baseline_3 + panas_baseline_9)/2,
         panas_beforetask_mean = (panas_beforetask_3 + panas_beforetask_9)/2,
         panas_aftertask_mean = (panas_aftertask_3 + panas_aftertask_9)/2,
         mf_baseline_mean = (mf_baseline_1 + mf_baseline_2 + mf_baseline_3 + mf_baseline_4)/4,
         vs_change = vs_end_avg_accuracy - vs_baseline_avg_accuracy,
         caffeine_perday = str_remove(caffeine_perday, " mg/day"),
         # Calculating cycle phase
         cycle_length = case_when(is.na(cycle_length) ~ 28, 
                                  cycle_length < 20 ~ 28,
                                  TRUE ~ cycle_length),
        across(ends_with("Date"), as.Date),
        days_between = onsite_RecordedDate - screener_RecordedDate,
        current_day = (as.numeric(cycle_day + days_between - 1) %% cycle_length) + 1,
        cycle_phase3 = case_when(current_day <= floor(2.75 / 7 * cycle_length) ~ "follicular",
                                current_day > floor(2.75 / 7 * cycle_length) & current_day <= floor((3.5) / 7 * cycle_length) ~ "ovulatory",
                                current_day > floor((3.5) / 7 * cycle_length) ~ "luteal",
                                TRUE ~ NA_character_) |> 
                        fct_relevel(c("follicular", "ovulatory", "luteal")),
        cycle_phase5 = case_when(current_day <= floor(1.75 / 7 * cycle_length) ~ "menstrual",
                                current_day > floor(1.75 / 7 * cycle_length) & current_day <= floor(3 / 7 * cycle_length) ~ "midfollicular",
                                current_day > floor(3 / 7 * cycle_length) & current_day <= floor(4 / 7 * cycle_length) ~ "ovulatory",
                                current_day > floor(4 / 7 * cycle_length) & current_day <= floor(5.25 / 7 * cycle_length) ~ "midluteal",
                                current_day > floor(5.25 / 7 * cycle_length) ~ "premenstrual",
                                TRUE ~ NA_character_) |> 
                        fct_relevel(c("menstrual", "midfollicular", "ovulatory", "midluteal", "premenstrual")))

```

## Pivoting to long format

```{r}
#Df's used will be: general_long (for everything not including cycle phases), cm_3_long (for 3-phase model) and cm_5_long (for 5-phase model)

woman_long <-                      
  woman_normcycle |>
  select(PARTICIPANT_ID,
          condition,
          age,
          contracept,
          cycle_length, cycle_day,
          cycle_phase3, cycle_phase5,
          caffeine_perday,
          panas_baseline = panas_baseline_mean, 
          panas_beforetask = panas_beforetask_mean, 
          panas_aftertask = panas_aftertask_mean, 
          eda_baseline = eda_avg_baseline, 
          eda_beforetask = eda_avg_before_task, 
          edaauc_baseline = eda_auc_baseline,
          edaauc_beforetask = eda_auc_before_task,
          vsaccuracy_baseline = vs_baseline_avg_accuracy, 
          vsaccuracy_end = vs_end_avg_accuracy, 
          vs_change,
          mf_baseline_mean) |>
  pivot_longer(cols = c(panas_baseline, panas_beforetask, panas_aftertask, eda_baseline, eda_beforetask, edaauc_baseline, edaauc_beforetask, vsaccuracy_baseline, vsaccuracy_end), 
               names_to = c("measure", "time"), 
               names_sep = "_", 
               values_to = "value") |>
  mutate(time = fct_relevel(time, "baseline", "beforetask", "aftertask", "end"))
```

## Exploratory data analysis

```{r}
# Descriptives
woman_normcycle %>%
  group_by(condition, contracept) %>%
  skim(panas_baseline_mean, panas_beforetask_mean, panas_aftertask_mean, eda_avg_baseline, eda_avg_before_task, eda_auc_baseline, eda_auc_before_task, caffeine_perday, mf_baseline_mean)

table(woman_normcycle$condition, woman_normcycle$contracept, woman_normcycle$cycle_phase3)

table(woman_normcycle$caffeine_perday)

woman_normcycle %>%
  group_by(condition) %>%
  skim(age, weight, contracept, cycle_length, cycle_phase3)

woman_normcycle %>%
  group_by(condition) %>%
  summarize(agemin = min(age),
            agemax = max(age),
            weightmin = min(weight),
            weightmax = max(weight),
            cyclemin = min(cycle_length),
            cyclemax = max(cycle_length))

# Manipulation check

manipulation_check_sa <- woman_long %>%
  filter(measure == "panas") %>%
  group_by(condition, time) %>%
  summarize(
    Subjective_Mean = mean(value, na.rm = TRUE),
    Subjective_SD = sd(value, na.rm = TRUE))
print(manipulation_check_sa)

summary_mancheck_sa <- woman_long %>%
  filter(measure == "panas") %>%
  group_by(time, condition) %>%
  summarize(
    mean_value = mean(value),
    se_value = sd(value) / sqrt(n())
  )
ggplot(summary_mancheck_sa, aes(x = time, y = mean_value, group = condition)) +
  geom_line(aes(color = condition), size = 1) +
  geom_point(aes(color = condition), size = 3) +
  geom_errorbar(aes(ymin = mean_value - se_value, ymax = mean_value + se_value, color = condition), 
                width = 0.2) +
  scale_x_discrete(labels = c("baseline" = "baseline", "beforetask" = "feladat előtt", "aftertask" = "feladat után")) +
  scale_color_discrete(labels = c("placebo", "koffein")) +
  labs(x = NULL, y = "Szubjektív arousal átlag",
    color = "Kísérleti feltétel"
  ) +
  theme(
    axis.title = element_text(family = "serif"),
    axis.text = element_text(family = "serif"),
    legend.title = element_text(family = "serif"),
    legend.text = element_text(family = "serif")
  )

manipulation_check_pa <- woman_long %>%
  filter(measure == "edaauc") %>%
  group_by(condition, time) %>%
  summarize(
    Physio_Mean = mean(value, na.rm = TRUE),
    Physio_SD = sd(value, na.rm = TRUE))
print(manipulation_check_pa)

summary_mancheck_pa <- woman_long %>%
  filter(measure == "edaauc", !is.na(value)) %>%
  group_by(time, condition) %>%
  summarize(
    mean_value = mean(value),
    se_value = sd(value) / sqrt(n())
  )
ggplot(summary_mancheck_pa, aes(x = time, y = mean_value, group = condition)) +
  geom_line(aes(color = condition), size = 1) +
  geom_point(aes(color = condition), size = 3) +
  geom_errorbar(aes(ymin = mean_value - se_value, ymax = mean_value + se_value, color = condition), 
                width = 0.2) +
  scale_x_discrete(labels = c("baseline" = "baseline", "beforetask" = "feladat előtt")) +
  scale_color_discrete(labels = c("placebo", "koffein")) +
  labs(x = NULL, y = "EDA AUC érték",
    color = "Kísérleti feltétel"
  ) +
  theme(
    axis.title = element_text(family = "serif"),
    axis.text = element_text(family = "serif"),
    legend.title = element_text(family = "serif"),
    legend.text = element_text(family = "serif")
  )

# Plotting PANAS

summary_panas <- woman_long %>%
  filter(measure == "panas") %>%
  group_by(time, condition, contracept) %>%
  summarize(
    mean_value = mean(value),
    se_value = sd(value) / sqrt(n())
  )

ggplot(summary_panas, aes(x = time, y = mean_value, group = interaction(condition, contracept))) +
  geom_line(aes(color = condition, linetype = contracept), size = 1) +
  geom_point(aes(color = condition, shape = contracept), size = 3) +
  geom_errorbar(aes(ymin = mean_value - se_value, ymax = mean_value + se_value, color = condition), 
                width = 0.2) +
  scale_x_discrete(labels = c("baseline" = "baseline", "beforetask" = "feladat előtt", "aftertask" = "feladat után")) +
  scale_color_discrete(labels = c("placebo", "koffein")) +
  scale_linetype_discrete(labels = c("Nem", "Igen")) +
  scale_shape_discrete(labels = c("Nem", "Igen")) +
  labs(x = NULL, y = "Szubjektív arousal átlag",
    color = "Kísérleti feltétel",
    linetype = "Fogamzásgátlási státusz",
    shape = "Fogamzásgátlási státusz"
  ) +
  theme(
    axis.title = element_text(family = "serif"),
    axis.text = element_text(family = "serif"),
    legend.title = element_text(family = "serif"),
    legend.text = element_text(family = "serif")
  )


summary_panas_2 <- woman_long %>%
  filter(measure == "panas", !is.na(cycle_phase3)) %>%
  group_by(time, cycle_phase3, contracept, condition) %>%
  summarize(
    mean_value = mean(value),
    se_value = sd(value) / sqrt(n())
  )

ggplot(summary_panas_2, aes(x = time, y = mean_value, group = interaction(cycle_phase3, contracept, condition))) +
  geom_line(aes(color = condition, linetype = contracept), size = 1) +
  geom_point(aes(color = condition, shape = cycle_phase3), size = 3) +
  geom_errorbar(aes(ymin = mean_value - se_value, ymax = mean_value + se_value, color = condition), 
                width = 0.2) +
  scale_x_discrete(labels = c("baseline" = "baseline", "beforetask" = "feladat előtt", "aftertask" = "feladat után")) +
   scale_color_discrete(labels = c("placebo", "koffein")) +
  scale_linetype_discrete(labels = c("Nem", "Igen")) +
  scale_shape_discrete(labels = c("follikuláris", "ovulációs", "luteális")) +
  labs(x = NULL, y = "Szubjektív arousal átlag",
    color = "Kísérleti feltétel",
    linetype = "Fogamzásgátlási státusz",
    shape = "Menstruációs ciklus aktuális szakasza"
  ) +
  theme(
    axis.title = element_text(family = "serif"),
    axis.text = element_text(family = "serif"),
    legend.title = element_text(family = "serif"),
    legend.text = element_text(family = "serif")
  )


# Plotting EDA
summary_edaauc <- woman_long %>%
  filter(measure == "edaauc", !is.na(value)) %>%
  group_by(time, condition, contracept) %>%
  summarize(
    mean_value = mean(value),
    se_value = sd(value) / sqrt(n())
  )

ggplot(summary_edaauc, aes(x = time, y = mean_value, group = interaction(condition, contracept))) +
  geom_line(aes(color = condition, linetype = contracept), size = 1) +
  geom_point(aes(color = condition, shape = contracept), size = 3) +
  geom_errorbar(aes(ymin = mean_value - se_value, ymax = mean_value + se_value, color = condition), 
                width = 0.2) +
  scale_x_discrete(labels = c("baseline" = "baseline", "beforetask" = "feladat előtt")) +
  scale_color_discrete(labels = c("placebo", "koffein")) +
  scale_linetype_discrete(labels = c("Nem", "Igen")) +
  scale_shape_discrete(labels = c("Nem", "Igen")) +
  labs(x = NULL, y = "EDA AUC érték",
    color = "Kísérleti feltétel",
    linetype = "Fogamzásgátlási státusz",
    shape = "Fogamzásgátlási státusz"
  ) +
  theme(
    axis.title = element_text(family = "serif"),
    axis.text = element_text(family = "serif"),
    legend.title = element_text(family = "serif"),
    legend.text = element_text(family = "serif")
  )


summary_edaauc_2 <- woman_long %>%
  filter(measure == "edaauc", !is.na(value), !is.na(cycle_phase3)) %>%
  group_by(time, cycle_phase3, contracept, condition) %>%
  summarize(
    mean_value = mean(value),
    se_value = sd(value) / sqrt(n())
  )

ggplot(summary_edaauc_2, aes(x = time, y = mean_value, group = interaction(cycle_phase3, contracept, condition))) +
  geom_line(aes(color = condition, linetype = contracept), size = 1) +
  geom_point(aes(color = condition, shape = cycle_phase3), size = 3) +
  geom_errorbar(aes(ymin = mean_value - se_value, ymax = mean_value + se_value, color = condition), 
                width = 0.2) +
  scale_x_discrete(labels = c("baseline" = "baseline", "beforetask" = "feladat előtt")) +
   scale_color_discrete(labels = c("placebo", "koffein")) +
  scale_linetype_discrete(labels = c("Nem", "Igen")) +
  scale_shape_discrete(labels = c("follikuláris", "ovulációs", "luteális")) +
  labs(x = NULL, y = "EDA AUC érték",
    color = "Kísérleti feltétel",
    linetype = "Fogamzásgátlási státusz",
    shape = "Menstruációs ciklus aktuális szakasza"
  ) +
  theme(
    axis.title = element_text(family = "serif"),
    axis.text = element_text(family = "serif"),
    legend.title = element_text(family = "serif"),
    legend.text = element_text(family = "serif")
  )

woman_normcycle %>%
  group_by(condition) %>%
  ggplot() +
  aes(x = eda_avg_baseline) +
  geom_bar()

woman_normcycle %>%
  filter(!is.na(eda_avg_baseline), !is.na(eda_avg_before_task), !is.na(eda_auc_baseline), !is.na(eda_auc_before_task)) %>%
  group_by(condition) %>%
  summarize(mean_eda_avg_baseline = mean(eda_avg_baseline),
            mean_eda_avg_beforetask = mean(eda_avg_before_task),
            mean_eda_auc_baseline = mean(eda_auc_baseline),
            mean_eda_auc_beforetask = mean(eda_auc_before_task))

woman_long %>%
  filter(measure == "eda") %>%
  group_by(condition) %>%
  ggplot() +
  aes(x = time, y = value, group = condition, color = condition) +
  stat_summary(geom = "pointrange") +
  labs(title = "Fiziológiai arousal az egyes mérési pontokban",
       x = NULL, y = NULL,
       color = "Kísérleti feltétel") +
  scale_x_discrete(labels = c("baseline" = "baseline", "beforetask" = "feladat előtt", "aftertask" = "feladat után")) +
  scale_color_discrete(labels = c("placebo", "koffein")) +
  theme_minimal()

woman_long %>%
  filter(measure == "eda", !is.na(cycle_phase3)) %>%
  ggplot() +
  aes(x = time, y = value) +
  stat_summary(geom = "pointrange") +
  facet_grid(condition ~ cycle_phase3) +
  labs(title = "Change in EDA values in the 3 cycle phases, by condition", x = NULL, y = NULL)

woman_long %>%
  filter(measure == "eda", !is.na(cycle_phase5)) %>%
  ggplot() +
  aes(x = time, y = value) +
  stat_summary(geom = "pointrange") +
  facet_grid(condition ~ cycle_phase5) +
  labs(title = "Change in EDA values in the 5 cycle phases, by condition", x = NULL, y = NULL)

# Plotting VS task
woman_long %>%
  filter(measure == "vsaccuracy") %>%
  ggplot() +
  aes(x = time, y = value) +
  stat_summary(geom = "pointrange") +
  labs(title = "Figyelmi feladat pontosság értékei az egyes mérési pontokban",
       x = NULL, y = NULL) +
  scale_x_discrete(labels = c("baseline" = "feladat elején", "end" = "feladat végén")) +
  theme_minimal()

woman_long %>%
  filter(measure == "vsaccuracy", !is.na(cycle_phase3)) %>%
  ggplot() +
  aes(x = time, y = value) +
  stat_summary(geom = "pointrange") +
  facet_grid(condition ~ cycle_phase3) +
  labs(title = "Change in VS task accuracy in the 3 cycle phases, by condition", x = NULL, y = NULL)

woman_long %>%
  filter(measure == "vsaccuracy", !is.na(cycle_phase5)) %>%
  ggplot() +
  aes(x = time, y = value) +
  stat_summary(geom = "pointrange") +
  facet_grid(condition ~ cycle_phase5) +
  labs(title = "Change in VS task accuracy in the 5 cycle phases, by condition", x = NULL, y = NULL)

woman_normcycle %>%
  filter(!is.na(cycle_phase3)) %>%
  ggplot() +
  aes(x = cycle_phase3, y = vs_change, fill = condition) +
  geom_boxplot() +
  geom_jitter() +
  labs(title = "Change of performance in the visual search task in the 3 cycle phases, by condition", x = NULL, y = NULL)

woman_normcycle %>%
  filter(!is.na(cycle_phase5)) %>%
  ggplot() +
  aes(x = cycle_phase5, y = vs_change, fill = condition) +
  geom_boxplot() +
  geom_jitter() +
  labs(title = "Change of performance in the visual search task in the 5 cycle phases, by condition", x = NULL, y = NULL)
```

## Building the models

```{r}
## Contrasts

contrasts(woman_long$time) <- contr.sum(levels(woman_long$time))
contrasts(woman_long$condition) <- contr.sum(levels(woman_long$condition))
contrasts(woman_long$cycle_phase3) <- contr.sum(levels(woman_long$cycle_phase3))
contrasts(woman_long$cycle_phase5) <- contr.sum(levels(woman_long$cycle_phase5))

contrasts(woman_long$time)
contrasts(woman_long$condition)
contrasts(woman_long$cycle_phase3)
contrasts(woman_long$cycle_phase5)

## Manipulation check

man_check_sa <-
  woman_long |> 
  filter(measure == "panas") |> 
  lmer(value ~ condition * time +
         caffeine_perday + mf_baseline_mean + 
         (1 | PARTICIPANT_ID),
       data = _)
summary(man_check_sa)
tab_model(man_check_sa, show.std = TRUE, show.se = TRUE)
pairwise_sa <- emmeans(man_check_sa, pairwise ~ condition * time)
summary(pairwise_sa)
effect_size_sa <- eff_size(pairwise_sa, sigma = sigma(man_check_sa), edf = df.residual(man_check_sa))
summary(effect_size_sa)


man_check_pa <-
  woman_long |> 
  filter(measure == "edaauc") |> 
  lmer(value ~ condition * time +
         caffeine_perday + mf_baseline_mean + 
         (1 | PARTICIPANT_ID),
       data = _)
summary(man_check_pa)
tab_model(man_check_pa, show.se = TRUE, show.std = TRUE)
pairwise_pa <- emmeans(man_check_pa, pairwise ~ condition * time)
effect_size_pa <- eff_size(pairwise_pa, sigma = sigma(man_check_pa), edf = df.residual(man_check_pa))
summary(effect_size_pa)

## Subjective arousal models
model_panas_1 <-
  woman_long |> 
  filter(measure == "panas") |> 
  lmer(value ~ condition * contracept * time +
         caffeine_perday + mf_baseline_mean + 
         (1 | PARTICIPANT_ID),
       data = _)
summary(model_panas_1)
tab_model(model_panas_1, show.std = TRUE, show.se = TRUE)
confint(model_panas_1)
check_collinearity(model_panas_1)
check_model(model_panas_1)
model_performance(model_panas_1)
emmeans(model_panas_1, pairwise ~ condition * time)
emmeans(model_panas_1, pairwise ~ time)



model_panas_2 <-
  woman_long |>
  filter(measure == "panas") |>
  lmer(value ~ condition * contracept * cycle_phase3 +
         condition * time +
         cycle_phase3 * time +
         caffeine_perday + mf_baseline_mean + 
         (1 | PARTICIPANT_ID), 
       data = _)
summary(model_panas_2)
tab_model(model_panas_2, show.std = TRUE, show.se = TRUE)
confint(model_panas_2)
check_collinearity(model_panas_2)
check_model(model_panas_2)
model_performance(model_panas_2)
anova(model_panas_1, model_panas_2)



model_panas_3 <-
  woman_long |>
  filter(measure == "panas") |>
  lmer(value ~ condition * contracept +
         condition * cycle_phase5 +
         condition * time +
         contracept * cycle_phase5 +
         caffeine_perday + mf_baseline_mean + 
         (1 | PARTICIPANT_ID), 
       data = _)
summary(model_panas_3)
confint(model_panas_3)
check_collinearity(model_panas_3)
check_model(model_panas_3)
emmeans(model_panas_3, pairwise ~ condition * contracept * cycle_phase5)
model_performance(model_panas_3)


## Physiological arousal models

model_eda_1 <-
  woman_long |>
  filter(measure == "eda") |>
  lmer(value ~ condition * contracept * time +
         caffeine_perday + mf_baseline_mean +
         (1 | PARTICIPANT_ID),
       data = _)
summary(model_eda_1)
tab_model(model_eda_1, show.std = TRUE, show.se = TRUE)
confint(model_eda_1)
check_collinearity(model_eda_1)
check_model(model_eda_1)
model_performance(model_eda_1)
emmeans(model_eda_1, pairwise ~ time)



model_eda_2 <-
  woman_long |>
  filter(measure == "eda") |>
  lmer(value ~ condition * contracept * cycle_phase3 +
         condition * time +
         cycle_phase3 * time +
         caffeine_perday + mf_baseline_mean +
         (1 | PARTICIPANT_ID),
       data = _)
summary(model_eda_2)
tab_model(model_eda_2, show.std = TRUE, show.se = TRUE)
confint(model_eda_2)
check_collinearity(model_eda_2)
check_model(model_eda_2)
model_performance(model_eda_2)



model_eda_3 <-
  woman_long |>
  filter(measure == "eda") |>
  lmer(value ~ condition * contracept * time + 
         condition * cycle_phase5 +
         caffeine_perday + mf_baseline_mean +
         (1 | PARTICIPANT_ID),
       data = _)
summary(model_eda_3)
confint(model_eda_3)
check_collinearity(model_eda_3)
check_model(model_eda_3)
model_performance(model_eda_3)

## EDA AUC model
model_auc_1 <-
  woman_long %>%
  filter(measure == "edaauc") |>
  lmer(value ~ condition * contracept * time +
         caffeine_perday + mf_baseline_mean +
         (1 | PARTICIPANT_ID),
       data = _)
summary(model_auc_1)
tab_model(model_auc_1, show.std = TRUE, show.se = TRUE)
model_performance(model_auc_1)
check_model(model_auc_1)

model_ranova_auc <- woman_long %>%
  filter(measure == "edaauc") |>
  aov(value ~ condition * time * contracept + Error(PARTICIPANT_ID / (condition * time)), data = _)
summary(model_ranova_auc)


model_auc_2 <-
  woman_long %>%
  filter(measure == "edaauc") |>
  lmer(value ~ condition * contracept * time +
         condition * contracept * cycle_phase3 +
         caffeine_perday + mf_baseline_mean +
         (1 | PARTICIPANT_ID),
       data = _)
summary(model_auc_2)
tab_model(model_auc_2, show.std = TRUE, show.se = TRUE)
model_performance(model_auc_2)
check_model(model_auc_2)
check_collinearity(model_auc_2)



## Visual search task models

model_vs_1 <-
  woman_long |>
  filter(measure == "vsaccuracy") |>
  lmer(value ~ condition * contracept * time +
         caffeine_perday + mf_baseline_mean +
         (1 | PARTICIPANT_ID),
       data = _)
summary(model_vs_1)
confint(model_vs_1)
check_collinearity(model_vs_1)
check_model(model_vs_1)
model_performance(model_vs_1)



fixed_effects_5 <- broom.mixed::tidy(model_vs_1, effects = "fixed", conf.int = TRUE)
ggplot(fixed_effects_5, aes(x = term, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  coord_flip() +  # Flip for better readability
  labs(title = "Főhatások, 95%-os konfidencia intervallumokkal",
       x = NULL,
       y = NULL)

model_vs_2 <-
  woman_long |>
  filter(measure == "vsaccuracy") |>
  lmer(value ~ condition * contracept * cycle_phase3 +
         condition * time +
         time * cycle_phase3 +
         caffeine_perday + mf_baseline_mean +
         (1 | PARTICIPANT_ID),
       data = _)
summary(model_vs_2)
confint(model_vs_2)
check_collinearity(model_vs_2)
check_model(model_vs_2)
model_performance(model_vs_2)

fixed_effects_6 <- broom.mixed::tidy(model_vs_2, effects = "fixed", conf.int = TRUE)
ggplot(fixed_effects_6, aes(x = term, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  coord_flip() +  # Flip for better readability
  labs(title = "Főhatások, 95%-os konfidencia intervallumokkal",
       x = NULL,
       y = NULL)

model_vs_3 <-
  woman_long |>
  filter(measure == "vsaccuracy") |>
  lmer(value ~ condition * contracept * time +
         condition * cycle_phase5 +
         caffeine_perday + mf_baseline_mean +
         (1 | PARTICIPANT_ID),
       data = _)
summary(model_vs_3)
confint(model_vs_3)
check_collinearity(model_vs_3)
check_model(model_vs_3)
model_performance(model_vs_3)

model_vschange_1 <-
  woman_long |>
  lm(vs_change ~ condition * contracept +
        caffeine_perday + mf_baseline_mean,
      data = _)
summary(model_vschange_1)
confint(model_vschange_1)
check_collinearity(model_vschange_1)
check_model(model_vschange_1)
model_performance(model_vschange_1)

fixed_effects_7 <- broom.mixed::tidy(model_vschange_1, effects = "fixed", conf.int = TRUE)
ggplot(fixed_effects_7, aes(x = term, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  coord_flip() +  # Flip for better readability
  labs(title = "Modell főhatások, 95%-os konfidencia intervallumokkal",
       x = NULL,
       y = NULL)

model_vschange_2 <-
  woman_long |>
  lm(vs_change ~ condition * contracept * cycle_phase3 +
        caffeine_perday + mf_baseline_mean,
      data = _)
summary(model_vschange_2)
confint(model_vschange_2)
check_collinearity(model_vschange_2)
check_model(model_vschange_2)
model_performance(model_vschange_2)
emmeans(model_vschange_2, pairwise ~ condition * contracept * cycle_phase3)

fixed_effects_8 <- broom.mixed::tidy(model_vschange_2, effects = "fixed", conf.int = TRUE)
ggplot(fixed_effects_8, aes(x = term, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  coord_flip() + # Flip coordinates for better readability
  labs(title = "Modell főhatások, 95%-os konfidencia intervallumokkal",
       x = NULL,
       y = "Teljesítményváltozás")

interaction_preds_1 <- ggpredict(model_vschange_2, terms = c("condition", "contracept", "cycle_phase3"))
plot(interaction_preds_1) +
  labs(title = "A kísérleti feltétel, a fogamzásgátlási státusz és a menstruációs ciklus fázisának interakciója",
       x = "Kísérleti feltétel",
       y = "Teljesítményváltozás")

model_vschange_3 <-
  woman_long |>
  lm(vs_change ~ condition * contracept +
       condition * cycle_phase5 +
       contracept * cycle_phase5 +
        caffeine_perday + mf_baseline_mean,
      data = _)
summary(model_vschange_3)
confint(model_vschange_3)
check_collinearity(model_vschange_3)
check_model(model_vschange_3)
model_performance(model_vschange_3)
  
```

## Visualizing models

```{r}
# PANAS models
coefficients <- fixef(model_panas_1)
woman_long %>%
  filter(measure == "panas") %>%
  summarize(sdvalue = sd(value))

fixed_effects_1 <- broom.mixed::tidy(model_panas_1, effects = "fixed", conf.int = TRUE)
ggplot(fixed_effects_1, aes(x = term, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  coord_flip() +
  labs(title = "Főhatások, 95%-os konfidencia intervallummal",
       x = NULL,
       y = NULL) +
  theme_minimal()

interaction_preds_2 <- ggpredict(model_panas_1, terms = c("condition", "time"))

predictions2 <- interaction_preds_2 %>%
  mutate(
    x = recode(x, 
               "condition" = "Feltétel",
               "time" = "Mérési pont")
  )

plot(interaction_preds_2) +
  labs(title = "A kísérleti feltétel és a mérési időpont interakciója",
       x = NULL,
       y = "Becsült szubjektív arousal",
       fill = "Mérési pont")

ranef_model <- ranef(model_panas_1, condVar = TRUE)
dotplot(ranef_model, scales = list(y = list(relation = "free")),
        main = "Caterpillar Plot of Random Effects")

fixed_effects_2 <- broom.mixed::tidy(model_panas_2, effects = "fixed", conf.int = TRUE)
ggplot(fixed_effects_2, aes(x = term, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  coord_flip() +
  labs(title = "Főhatások, 95%-os konfidencia intervallumokkal",
       x = NULL,
       y = NULL) +
  theme_minimal()

## EDA models


fixed_effects_3 <- broom.mixed::tidy(model_eda_1, effects = "fixed", conf.int = TRUE)
ggplot(fixed_effects_3, aes(x = term, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  coord_flip() +  # Flip for better readability
  labs(title = "Főhatások, 95%-os konfidencia intervallumokkal",
       x = NULL,
       y = NULL)

fixed_effects_4 <- broom.mixed::tidy(model_eda_2, effects = "fixed", conf.int = TRUE)
ggplot(fixed_effects_4, aes(x = term, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  coord_flip() +  # Flip for better readability
  labs(title = "Főhatások, 95%-os konfidencia intervallumokkal",
       x = NULL,
       y = NULL)

fixed_effects_auc1 <- broom.mixed::tidy(model_auc_1, effects = "fixed", conf.int = TRUE)
ggplot(fixed_effects_auc1, aes(x = term, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  coord_flip() +
  labs(title = "Főhatások, 95%-os konfidencia intervallummal",
       x = NULL,
       y = NULL) +
  theme_minimal()

interaction_preds_auc <- ggpredict(model_auc_1, terms = c("condition", "contracept"))
plot(interaction_preds_auc) +
  labs(title = "A kísérleti feltétel és a fogamzásgátlás használatának interakciója",
       x = NULL,
       y = "Fiziológiai arousal AUC",
       color = "Fogamzásgátlás használata") +
  scale_color_discrete(labels = c("nem használ", "használ"))

fixed_effects_auc2 <- broom.mixed::tidy(model_auc_2, effects = "fixed", conf.int = TRUE)
ggplot(fixed_effects_auc2, aes(x = term, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  coord_flip() +
  labs(title = "Főhatások, 95%-os konfidencia intervallummal",
       x = NULL,
       y = NULL) +
  theme_minimal()
```



